### ISSUE TITLE
Fix intermittent test failure in integration.ts

### ISSUE THREAD

**Issue by cd1m0** [Consensys/souffle.ts#10]
The test starting on line 58 in `integration.ts` fails in CI and *sometimes* locally, but *sometimes* it works. It feels like something weird is happening when getting the output from the sub-process with large files.

Perhaps we can make it simpler by outputing to a local file instead of trying to read the stdout of the sub-process.

**Comment by blitz-1306** [comment]
I actually think that Jest is not necessarily good at handling subprocesses. Try to check #15 locally - should be stable.
